apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-microservice
  labels:
    app: k8s-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-microservice
  template:
    metadata:
      labels:
        app: k8s-microservice
    spec:
      serviceAccountName: k8s-microservice
      containers:
      - name: microservice
        image: k8s-microservice:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"